// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbj_qfsRcIgJg4aXaDvEYa8qo9lgUiQ-g',
    appId: '1:321413938644:web:0a0d436de9b82b2c06ea41',
    messagingSenderId: '321413938644',
    projectId: 'testpune',
    authDomain: 'testpune.firebaseapp.com',
    storageBucket: 'testpune.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpaniWR5pkPkcys5aSeMEwhnbOod8cpZ0',
    appId: '1:321413938644:android:2fd1c78c03e9a09206ea41',
    messagingSenderId: '321413938644',
    projectId: 'testpune',
    storageBucket: 'testpune.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyQjfy1Lx-2lXzqBZANi94xpn8-BkhHcc',
    appId: '1:321413938644:ios:d6b191952a0abc4306ea41',
    messagingSenderId: '321413938644',
    projectId: 'testpune',
    storageBucket: 'testpune.firebasestorage.app',
    iosBundleId: 'com.example.vigorushealthcaretest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyQjfy1Lx-2lXzqBZANi94xpn8-BkhHcc',
    appId: '1:321413938644:ios:d6b191952a0abc4306ea41',
    messagingSenderId: '321413938644',
    projectId: 'testpune',
    storageBucket: 'testpune.firebasestorage.app',
    iosBundleId: 'com.example.vigorushealthcaretest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbj_qfsRcIgJg4aXaDvEYa8qo9lgUiQ-g',
    appId: '1:321413938644:web:32e8d4be332ede5a06ea41',
    messagingSenderId: '321413938644',
    projectId: 'testpune',
    authDomain: 'testpune.firebaseapp.com',
    storageBucket: 'testpune.firebasestorage.app',
  );
}
